#!/usr/bin/env bash
#comment to 10-fizzbuzz
i=1
while ((i<=100)); do
	if (( i%3==0 & i%5==o )); then
		echo "FizzBuzz"
	elif (( i%3==0 )); then
		echo "Fizz"
	elif (( i%5==o)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
