#!/usr/bin/env bash
#jus a comment for passwd task
IFS=":"
while read -r line; do
	name=$(echo "$line" | cut -d : -f1)
	gid=$(echo "$line" | cut -d : -f4)
	home=$(echo "$line" | cut -d: -f6)
	shell=$(echo "$line" | cut -d : -f7)
	password=$(echo "$line" | cut -d: -f2)
	uid=$(echo "$line" | cut -d : -f3)
	echo "The user $name is part of the $gid  gang, lives in $home and rides $shell . USER ID's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd
